### ISSUE TITLE
Transfer doesn't work

### ISSUE THREAD

**Issue by tplk** [nicoschmitt/necrobotvisualizer#39] opened 2016-08-01 18:59 UTC
Using v1.0.6, After clicking on trash can icon pokemon fades away from the list but isn't transferred and appears again after refresh.

**Comment by niicojs** [comment] 2016-08-01 19:03
it's probably because it has not been implemented on the bot you are using. only necrobot run from source code as of today

**Comment by Epinikion** [comment] 2016-08-01 19:06
It works fine with my last build of necrobot (and nicos pullrequest) from 3hrs ago. So, no bug :)

**Comment by degree8th** [comment] 2016-08-01 19:06
Using  v1.0.6 + necro 0.5 released in 20 hours ago  the transfer is not working.

**Comment by tplk** [comment] 2016-08-01 19:13
> Using v1.0.6 + necro 0.5 released in 20 hours ago the transfer is not working.

Yeah.
Ok. Will wait till new version is released.

**Comment by li81** [comment] 2016-08-01 19:15
Using v1.0.6 + necro 0.5 released in 20 hours ago the transfer is not working.

Confirmed.

**Comment by niicojs** [comment] 2016-08-01 21:11
Wait for a release or build the bot from the source. Closing.

**Closed as completed by niicojs** 2016-08-01 21:11 UTC
Labels: bug
