### ISSUE TITLE
New idea's

### ISSUE THREAD

**Issue by li81** [nicoschmitt/necrobotvisualizer#37] opened 2016-08-01 18:01 UTC
Hello, I will post some idea's here about the bot.
1. Multiple bot support, each bot get it's own tab. (Like browsers have)
2. Sort Pokemon by name.
3. favourite pokemon.
4. Total pokemon count (0/250).
   5.. Delete items, with ammount to delete.
5. Total item count (0/350).
6. Add name, runtime, level, stardust etc (Like necrobot has)

Thats it for now.

P.S. I like your work, keep it up! And if you need more idea's or testers, feel free to add me on skype.

**Comment by li81** [comment] 2016-08-01 18:06
@nicoschmitt Check it out.

**Comment by niicojs** [comment] 2016-08-01 18:13
thanks for the features list!
- I've implemented sort by # which should get what you need.
- total item/pokemon count is a good idea.
- multi-bot is not on my todo list for now, sorry
- delete item on my list
- name, runtime, etc... to be considered. most people run both on the same machine so info is just on the other window next to it I guess

**Comment by li81** [comment] 2016-08-01 18:21
Hmm, # is not exactly what I need. I want the pokemon to sort by name so I see 5 snorlax in a row and not seperated :P 

Also, what is the reason for the multi-bot? Too much work? It would be so much easier, now it just picks a random bot, I can't choose which bot I want to follow :(

**Comment by BinguinBabaja** [comment] 2016-08-01 18:32
You can choose the bot... just set a different port in each config and use that port in the visualizer then.
However Multi-Bot support would be very nice

**Comment by li81** [comment] 2016-08-01 18:35
Can you explain this to me? I would love to see my other bots too. I have no clue how to config this.

**Comment by niicojs** [comment] 2016-08-01 18:41
you mean grouping by name  ? or sorting by name ?
cause for me sorting by name or id is quite the same

**Comment by li81** [comment] 2016-08-01 18:42
Like this: 
![1234](https://cloud.githubusercontent.com/assets/1375379/17304946/645fdb5c-5828-11e6-8855-4014e3658e49.jpg)

**Comment by niicojs** [comment] 2016-08-01 18:42
if you sort by pokemon id you should get the same

**Comment by li81** [comment] 2016-08-01 18:43
I did sort by # : http://puu.sh/qmf7b/39fc3ce445.jpg

**Comment by dacas3** [comment] 2016-08-01 18:54
Can confirm what li81 is writing, sorting by # is not working as intended

not sure what it's sorting it by even, it looks random, maybe pokemon age? :p

**Comment by niicojs** [comment] 2016-08-01 18:56
ok, that's a bug :)

**Comment by Epinikion** [comment] 2016-08-01 19:34
- maybe add to catch event popup which ball was used?

**Comment by niicojs** [comment] 2016-08-01 21:42
sort fixing, showing pokell and object count is done for 1.0.7
I'll let you open issue for individual features next time.
closing this one.

**Closed as completed by niicojs** 2016-08-01 21:42 UTC
Labels: bug, enhancement, in progress
