### ISSUE TITLE
Compatibility with Necrobot 0.7.0

### ISSUE THREAD

**Issue by MyUncleSam** [nicoschmitt/necrobotvisualizer#103] opened 2016-08-07 11:49 UTC
Hi there,

the visualizer is able to connect to the webservice (after switching the new property "UseWebsocket" to true.

There are following issues:
- Not displaying the position / walk paths
- Inventar, pokemons and pokeballs can not be viewed

It seems it can get one position at launch but everything else seems to be not working currently.

**Comment by EpicLPer** [comment] 2016-08-07 12:08
Additional it cannot grab Pokestops anymore, but that's probably due to the new way they distribute those (which also broke Necrobot for a long time)

**Comment by halvors** [comment] 2016-08-07 12:13
I am also have this exactly same issue.

**Comment by blackms** [comment] 2016-08-07 12:19
Same.

**Comment by GraspGG** [comment] 2016-08-07 14:24
Same here.

Walk path gets updated once after using save button within settings. Maybe that helps.

**Comment by RentonXD** [comment] 2016-08-07 14:24
Does it work for you? my visualizer is just saying 'Connecting to the bot...' o.O

**Comment by brokenmass** [comment] 2016-08-07 14:43
I think the issue is in the bot code , not in the visualizer

**Comment by RentonXD** [comment] 2016-08-07 14:56
ah damn.. yea my fault sry.. ^^'

**Comment by Energex22** [comment] 2016-08-07 15:10
Having the same problems, i can update my path by opening settings and closing again, but yet no pokemon, pokestops or anything appears...

**Comment by Molier** [comment] 2016-08-07 15:49
any word on a compatible, working visualizer?

**Comment by TheMaskedMonkey** [comment] 2016-08-07 16:17
By default `UseWebsocket` is set to false. (It was in the changelog) - Set it to true and the map will work again.

**Comment by plopingo** [comment] 2016-08-07 16:30
stuck at 'Connecting to the bot...'

**Comment by Fourhundred57** [comment] 2016-08-07 17:27
Looks like things are up and running now that NecroBot has been updated!

**Comment by TheEpTic** [comment] 2016-08-07 17:31
Yeah, can confirm 0.7.2 fixed this.

**Comment by blackpilgrim** [comment] 2016-08-07 17:42
I'm still stuck at "connecting to the bot" even though i already use the 0.7.2

**Comment by EpicLPer** [comment] 2016-08-07 17:46
@blackpilgrim You need to enable the Websocket in config.json first.

**PS.: VISUALIZER WORKS WITH 0.7.2 AGAIN! ISSUE CAN BE CLOSED!**

**Comment by niicojs** [comment] 2016-08-07 17:46
thanks all, I like when an issue resolve itself :)

**Closed as completed by niicojs** 2016-08-07 17:46 UTC
