### ISSUE TITLE
Pokemon icon offsets are off

### ISSUE THREAD

**Issue by GediminasMasaitis** [nicoschmitt/necrobotvisualizer#74] opened 2016-08-02 17:56 UTC
Take for example this slowbro:

![image](https://cloud.githubusercontent.com/assets/7861188/17339146/3ca8f73a-58f3-11e6-8c94-fdbcc158d48d.png)

Looks like it was sniped in the middle of the ocean. However, when zooming in closer:

![image](https://cloud.githubusercontent.com/assets/7861188/17339169/5673971a-58f3-11e6-8307-f4ef2d96f072.png)

You can see that it was actually in Boston.

I think a solution would be to place the center of the image at the capture point, not the upper left corner.

**Comment by niicojs** [comment] 2016-08-02 18:17
Could you check and do it yourself?

**Comment by niicojs** [comment] 2016-08-02 19:28
I did a small fix in source tree but not quite perfect

**Comment by Epinikion** [comment] 2016-08-02 19:29
`.pkmIcon {
  max-height: 45px;
  margin: -10px 0 0 -26px;
}`

in app.css could be a easy fix so it matches position a bit more accurate on greater viewsclae, not sure whats the right value for that. Not best practice but u don't have to mess with the map marker code itself

**Comment by Epinikion** [comment] 2016-08-02 19:32
Ahh i see u did a better fix with anchor :)

**Comment by niicojs** [comment] 2016-08-02 19:33
better I don't know. the issue is that icon size really depend on the pokemon, some are wide some are tall so anchor should be a percentage but I didn't find how to do that

**Comment by Epinikion** [comment] 2016-08-02 19:53
but it is almost right, cause u fixed width and height to maximum so it should anchor 30 on width i guess. good enough i think :) leaflet has no option to get the actual image size, thats bad :(

**Comment by niicojs** [comment] 2016-08-02 20:26
let's close it for now

**Closed as completed by niicojs** 2016-08-02 20:26 UTC
Labels: bug, help wanted
